// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Las migraciones (CLI) necesitan una conexión directa, no pooled: los
    // advisory locks que usa `migrate deploy` no funcionan bien a través del
    // pooler de Neon/pgbouncer. Vercel expone la directa como
    // DATABASE_URL_UNPOOLED; en local, donde no existe, usamos DATABASE_URL.
    url: process.env["DATABASE_URL_UNPOOLED"] || process.env["DATABASE_URL"],
  },
});
